version: "2"
services: 
  ydl:
    container_name: ydl
    network_mode: bridge
    image: tzahi12345/youtubedl-material
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ydl.entrypoints=web"
      - "traefik.http.routers.ydl.rule=Host(`ydl.eriri.lan`)"
      - "traefik.http.services.ydl.loadbalancer.server.port=17442"
