version: "2"
services: 
  emby:
    container_name: emby
    network_mode: bridge
    image: emby/embyserver:latest
    restart: unless-stopped
    volumes:
      - "emby_volumes:/config"
      - "/home/${USER}/zfs-f:/zfs-f"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.entrypoints=web"
      - "traefik.http.routers.emby.rule=Host(`emby.eriri.lan`)"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
    ports:
      - 44008:8096

volumes:
    emby_volumes:
