version: "3"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    network_mode: bridge
    restart: unless-stopped
    command:
      # Globals
      - "--log.level=DEBUG"
      - "--api=true"
      - "--global.sendAnonymousUsage=false"
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Entrypoints
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # API
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.vm.ashurin.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
